# Creating tensors using data 

In [1]:
import numpy as np         # import dependencies
import torch

In [2]:
data = np.array([1, 2, 3])
type(data)                   # check the data type - numpy array!

numpy.ndarray

In [7]:
# passing in the values to the tensor

torch.Tensor(data)  # always takes up the default dtype

tensor([1., 2., 3.])

In [3]:
torch.tensor(data)   # looks up at the data and then decide its dtype

tensor([1, 2, 3], dtype=torch.int32)

In [4]:
# if it were a float type  ('.' after the number shows its float type with all the decimal values after the point to be 0)
data = np.array([1., 2., 3.])

torch.tensor(data)

tensor([1., 2., 3.], dtype=torch.float64)

In [5]:
torch.as_tensor(data)     

tensor([1., 2., 3.], dtype=torch.float64)

In [6]:
torch.from_numpy(data)    # directly via numpy

tensor([1., 2., 3.], dtype=torch.float64)

# Creating tensor without data beforehand


In [15]:
# return identity tensor / matrix

torch.eye(5)  # 2 is the number of rows and columns in the square matrix/tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
# Zeros tensor 

torch.zeros(2,4)                # 2 rows and 4 columns

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Ones in the tensor

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# random value generation

torch.rand(3,4)

tensor([[0.7958, 0.3195, 0.9956, 0.6234],
        [0.3407, 0.3906, 0.8533, 0.4985],
        [0.0895, 0.2199, 0.2518, 0.7485]])

In [13]:
# want change the dtype from the default float32 to float64 

# checking default dtype
torch.get_default_dtype()

torch.float32

In [14]:
# change it by simply defining the dtype

torch.tensor(np.array([1, 2, 3]), dtype = torch.float64)  

tensor([1., 2., 3.], dtype=torch.float64)

# Test question and solution

In [22]:
data = np.array([1, 2, 3])

t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

data[0] = 0
data[1] = 0
data[2] = 0

# what would be the result if we print t1, t2, t3, t4

print("t1 = ", t1)
print("t2 = ", t2)
print("t3 = ", t3)
print("t4 = ", t4)

t1 =  tensor([1., 2., 3.])
t2 =  tensor([1, 2, 3], dtype=torch.int32)
t3 =  tensor([0, 0, 0], dtype=torch.int32)
t4 =  tensor([0, 0, 0], dtype=torch.int32)
