# Element-wise operations

## Arithmetic operations

In [3]:
import torch

t1 = torch.tensor([[1, 2],
                   [3, 4]], dtype = torch.float32)

t2 = torch.tensor([[9, 8],
                   [7, 6]], dtype = torch.float32)

In [4]:
# addition 

t1 + t2

tensor([[10., 10.],
        [10., 10.]])

In [5]:
# substraction

t1 - t2

tensor([[-8., -6.],
        [-4., -2.]])

In [6]:
# multiplication 

t1 * t2

tensor([[ 9., 16.],
        [21., 24.]])

In [8]:
# division

t2 / t1

tensor([[9.0000, 4.0000],
        [2.3333, 1.5000]])

## Example with arithemetic operation not following same size rule!

In [9]:
# Addition - adding 2 to all the elements in t1
# Method - 1 
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [10]:
# Method - 2 

t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [11]:
# Substraction - removing 2 to all the elements in t1
# Method - 1 
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [12]:
# Method - 2 

t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [13]:
# Multiplication - multiply with 2 to all the elements in t1
# Method - 1 
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [14]:
# Method - 2 
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [15]:
# Division - diving by 2 to all the elements in t1
# Method - 1 
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [16]:
# Method - 2 
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

# Broadcasting of tensors

In [17]:
# when we perform " t1 + 2 ", under the hood, by broadcasting its shape is changed to that of t1

import numpy as np

np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [18]:
# technically, making " t1 + 2 " be equivalent to the below behind the scenes

t1 + torch.tensor(np.broadcast_to(2, t1.shape), dtype = torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [19]:
# check the above result
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

## Adding tensors of different shapes 

## Addition of [2, 2] tensor with [1, 2] tensor

In [21]:
t1 = torch.tensor([[1, 1],                                    
                   [1, 1]], dtype = torch.float32)

t2 = torch.tensor([2, 4], dtype = torch.float32)
                   
# add the two

t1 + t2

tensor([[3., 5.],
        [3., 5.]])

In [22]:
# under the hood , broadcasting occurs and will look something like this

# broadcasting on t2 to match their shapes

np.broadcast_to(t2.numpy(), t1.shape)


array([[2., 4.],
       [2., 4.]], dtype=float32)

In [24]:
# final result

t1 + torch.tensor(np.broadcast_to(t2.numpy(), t1.shape))

tensor([[3., 5.],
        [3., 5.]])

## Addition of [2, 2] tensor with [2, 1] tensor

In [28]:
t1 = torch.tensor([[2, 1],                                    
                   [1, 2]], dtype = torch.float32)

t2 = torch.tensor([[2], 
                  [4]] , dtype = torch.float32)
# add the two

t1 + t2

tensor([[4., 3.],
        [5., 6.]])

In [29]:
# under the hood , broadcasting occurs and will look something like this

# broadcasting on t2 to match their shapes

np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 2.],
       [4., 4.]], dtype=float32)

In [30]:
# final result

t1 + torch.tensor(np.broadcast_to(t2.numpy(), t1.shape))

tensor([[4., 3.],
        [5., 6.]])

In [38]:
# same rank, diff. shape

t1 = torch.tensor ([[1, 2, 3],], dtype = torch.float32)
t1.size()

torch.Size([1, 3])

In [39]:
t2 = torch.tensor ([[4],
                    [5],
                    [6]], dtype = torch.float32)
t2.size()

torch.Size([3, 1])

In [41]:
len(t1.shape)   # rank 2 similarly len(t2.shape) is also 2 

2

In [42]:
t1 + t2

tensor([[5., 6., 7.],
        [6., 7., 8.],
        [7., 8., 9.]])

In [44]:
# Different "rank" , different shape

t1 = torch.tensor ([[1, 2, 3],], dtype = torch.float32)     # rank = 2
t1.shape

torch.Size([1, 3])

In [46]:
t2 = torch.tensor ([5], dtype = torch.float32)     # rank = 1
t2.shape

torch.Size([1])

In [49]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[5., 5., 5.]], dtype=float32)

In [48]:
t1 * t2

tensor([[ 5., 10., 15.]])

In [51]:
#Different "rank" , different shape BUT NOT compatible! 
#So, NO broadcasting! Hence, arithmetic operation cannot be performed.

t1 = torch.tensor([[1, 2, 3],                                    
                   [4, 5, 6]], dtype = torch.float32)
t1.shape

torch.Size([2, 3])

In [52]:
t2 =  torch.tensor([[4, 4, 4],
                    [5, 5, 5],
                    [6, 6, 6]], dtype = torch.float32)
t2.shape

torch.Size([3, 3])

In [53]:
t1 + t2

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

# Comparison Operations

In [54]:
 t = torch.tensor([[0, 4, 1],
                    [5, 0, 5],
                    [6, 6, 0]], dtype = torch.float32)

In [55]:
# Equal to  
t.eq(0)        # element equal to '0' as asked are shown as '1' i.e., true 

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.uint8)

In [56]:
# greater than equal to ( >= )
t.ge(0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [57]:
# less than equal to ( <= )
t.le(0)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.uint8)

In [58]:
# greater than ( > )
t.gt(0)


tensor([[0, 1, 1],
        [1, 0, 1],
        [1, 1, 0]], dtype=torch.uint8)

In [59]:
# less than ( < )
t.lt(0)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

# Example Using Functions

In [60]:
# Absolute value
t.abs()

tensor([[0., 4., 1.],
        [5., 0., 5.],
        [6., 6., 0.]])

In [61]:
# Square root
t.sqrt()

tensor([[0.0000, 2.0000, 1.0000],
        [2.2361, 0.0000, 2.2361],
        [2.4495, 2.4495, 0.0000]])

In [62]:
# negation
t.neg()

tensor([[-0., -4., -1.],
        [-5., -0., -5.],
        [-6., -6., -0.]])

In [63]:
# negation and absolute value
t.neg().abs()

tensor([[0., 4., 1.],
        [5., 0., 5.],
        [6., 6., 0.]])

# Reduction Operations

In [64]:
# summation of elements
t.sum()

tensor(27.)

In [65]:
# no of elements
t.numel()

9

In [66]:
# no of elements in sum
t.sum().numel()

1

In [67]:
#comparison
t.sum().numel() < t.numel()

True

In [68]:
t.prod()

tensor(0.)

In [69]:
t.mean()

tensor(3.)

In [70]:
t.std()

tensor(2.6926)

In [71]:
# at certain axis
t[0].sum()

tensor(5.)

In [72]:
t.sum(dim=1)

tensor([ 5., 10., 12.])

# Argmax Tensor reduction operation:


In [73]:
t.max()

tensor(6.)

In [74]:
t.argmax()       # index of the max value from flattened tensor

tensor(7)

In [75]:
t.flatten()

tensor([0., 4., 1., 5., 0., 5., 6., 6., 0.])