# Reshaping of Tensors

In [1]:
# import the dependencies

import torch

In [17]:
# to check the shape or size of the tensor

t = torch.tensor([
                  [1, 1, 1, 1],
                  [2, 2, 2, 2],
                  [3, 3, 3, 3]] , dtype = torch.float32)

# using .size
t.size()


torch.Size([3, 4])

In [19]:
# using .shape , writing .shape() will give an error
t.shape

torch.Size([3, 4])

In [21]:
# calculate the dimension or the rank

len(t.shape)

2

In [22]:
# to find the no of elements 

# 1 a combination using product
torch.tensor(t.shape).prod()

tensor(12)

In [23]:
# directly using numel() , no of elements
t.numel()

12

# # Reshaping without changing the rank

In [24]:
t.reshape(1, 12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [25]:
t.reshape(3, 4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [26]:
t.reshape(6, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [27]:
t.reshape(4, 3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

# # Reshaping with the change of tensor rank

In [31]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [37]:
# t is not effected

t.size()

torch.Size([3, 4])

In [38]:
print(t)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


In [39]:
a = t.reshape(2,2,3)

print(a)
a.size()

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])


torch.Size([2, 2, 3])

In [36]:
len(a.shape)


3

# Squeezing and unsqueezing of tensors

# # Squeezing of tensors

In [47]:
# remove the 1's from the dimentions or axes that have a length of 1
# taking the above tensor "t"

print(" d before squeezing = " , t.reshape(1, 12))

t.reshape(1, 12).size()

 d before squeezing =  tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])


torch.Size([1, 12])

In [48]:
print("d after squeezing", t.reshape(1, 12).squeeze() )

t.reshape(1, 12).squeeze().size()

d after squeezing tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


torch.Size([12])

In [43]:
d = torch.ones(2, 1, 2, 1)

print(" d before squeezing = " , d)

d.size()



 d before squeezing =  tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])


torch.Size([2, 1, 2, 1])

In [44]:
print("d after squeezing", d.squeeze() )

d.squeeze().size()

d after squeezing tensor([[1., 1.],
        [1., 1.]])


torch.Size([2, 2])

# # unsqueezing of tensors

In [49]:
print("t before unsqueezing", t.reshape(1, 12).squeeze() )

t.reshape(1, 12).squeeze().size()

t before unsqueezing tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


torch.Size([12])

In [51]:
print("t after unsqueezing", t.reshape(1, 12).squeeze().unsqueeze(dim=0) )

t.reshape(1, 12).squeeze().unsqueeze(dim=0).size()

t after unsqueezing tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])


torch.Size([1, 12])

In [52]:
print(" d before unsqueezing = " , d.squeeze())

d.squeeze().size()

 d before unsqueezing =  tensor([[1., 1.],
        [1., 1.]])


torch.Size([2, 2])

In [59]:
print("d after unsqueezing", d.squeeze().unsqueeze(dim=1) )

d.squeeze().unsqueeze(dim=1).size()

d after unsqueezing tensor([[[1., 1.]],

        [[1., 1.]]])


torch.Size([2, 1, 2])

In [57]:
print("d after unsqueezing", d.squeeze().unsqueeze(dim=1).unsqueeze(dim=3) )

d.squeeze().unsqueeze(dim=1).unsqueeze(dim=3).size()

d after unsqueezing tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]])


torch.Size([2, 1, 2, 1])

#  Concatenation of tensors

In [64]:
# row-wise concatenation

t1 = torch.tensor([
                [1, 2],
                [3, 4]])

t2 = torch.tensor([
                [5, 6],
                [7, 8]])


torch.cat((t1, t2), dim = 0 )    # along axis =0

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [65]:
torch.cat((t1, t2), dim = 0 ).size()

torch.Size([4, 2])

In [61]:
# column wise concatenation 

torch.cat((t1, t2), dim = 1 )    # along axis =1

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [66]:
torch.cat((t1, t2), dim = 1 ).size()

torch.Size([2, 4])

# Flattening of tensor

In [72]:
c = torch.rand([3,3,4])
c

tensor([[[0.8080, 0.8655, 0.0567, 0.3146],
         [0.1281, 0.5294, 0.1896, 0.5583],
         [0.3436, 0.2186, 0.3383, 0.4740]],

        [[0.2093, 0.9429, 0.1235, 0.5228],
         [0.5886, 0.6063, 0.9923, 0.5419],
         [0.3559, 0.8813, 0.8436, 0.6621]],

        [[0.9658, 0.4026, 0.9307, 0.6241],
         [0.2411, 0.4678, 0.4807, 0.9927],
         [0.3575, 0.9946, 0.3178, 0.5948]]])

In [70]:
torch.flatten(c)

tensor([0.1763, 0.5723, 0.0550, 0.8644, 0.2522, 0.0405, 0.0067, 0.6827, 0.2268,
        0.9955, 0.2270, 0.1352, 0.7395, 0.1368, 0.5523, 0.9141, 0.3370, 0.3372,
        0.2300, 0.3069, 0.7214, 0.2030, 0.8448, 0.9745, 0.0958, 0.7030, 0.5816,
        0.5972, 0.0371, 0.9758, 0.5316, 0.3106, 0.9344, 0.1847, 0.9176, 0.6779])

In [73]:
torch.flatten(c).size()

torch.Size([36])

In [75]:
torch.flatten(c , start_dim = 1)

tensor([[0.8080, 0.8655, 0.0567, 0.3146, 0.1281, 0.5294, 0.1896, 0.5583, 0.3436,
         0.2186, 0.3383, 0.4740],
        [0.2093, 0.9429, 0.1235, 0.5228, 0.5886, 0.6063, 0.9923, 0.5419, 0.3559,
         0.8813, 0.8436, 0.6621],
        [0.9658, 0.4026, 0.9307, 0.6241, 0.2411, 0.4678, 0.4807, 0.9927, 0.3575,
         0.9946, 0.3178, 0.5948]])

In [76]:
torch.flatten(c , start_dim = 2)

tensor([[[0.8080, 0.8655, 0.0567, 0.3146],
         [0.1281, 0.5294, 0.1896, 0.5583],
         [0.3436, 0.2186, 0.3383, 0.4740]],

        [[0.2093, 0.9429, 0.1235, 0.5228],
         [0.5886, 0.6063, 0.9923, 0.5419],
         [0.3559, 0.8813, 0.8436, 0.6621]],

        [[0.9658, 0.4026, 0.9307, 0.6241],
         [0.2411, 0.4678, 0.4807, 0.9927],
         [0.3575, 0.9946, 0.3178, 0.5948]]])

In [94]:
torch.flatten(c , start_dim = 0 , end_dim = 1)


tensor([[0.8080, 0.8655, 0.0567, 0.3146],
        [0.1281, 0.5294, 0.1896, 0.5583],
        [0.3436, 0.2186, 0.3383, 0.4740],
        [0.2093, 0.9429, 0.1235, 0.5228],
        [0.5886, 0.6063, 0.9923, 0.5419],
        [0.3559, 0.8813, 0.8436, 0.6621],
        [0.9658, 0.4026, 0.9307, 0.6241],
        [0.2411, 0.4678, 0.4807, 0.9927],
        [0.3575, 0.9946, 0.3178, 0.5948]])

In [74]:
c.reshape(-1)

tensor([0.8080, 0.8655, 0.0567, 0.3146, 0.1281, 0.5294, 0.1896, 0.5583, 0.3436,
        0.2186, 0.3383, 0.4740, 0.2093, 0.9429, 0.1235, 0.5228, 0.5886, 0.6063,
        0.9923, 0.5419, 0.3559, 0.8813, 0.8436, 0.6621, 0.9658, 0.4026, 0.9307,
        0.6241, 0.2411, 0.4678, 0.4807, 0.9927, 0.3575, 0.9946, 0.3178, 0.5948])

In [79]:
c.view(c.numel())

tensor([0.8080, 0.8655, 0.0567, 0.3146, 0.1281, 0.5294, 0.1896, 0.5583, 0.3436,
        0.2186, 0.3383, 0.4740, 0.2093, 0.9429, 0.1235, 0.5228, 0.5886, 0.6063,
        0.9923, 0.5419, 0.3559, 0.8813, 0.8436, 0.6621, 0.9658, 0.4026, 0.9307,
        0.6241, 0.2411, 0.4678, 0.4807, 0.9927, 0.3575, 0.9946, 0.3178, 0.5948])